### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-json-web-tokens#17]
The **jwt.verify** method is going to be (one of) the most intensely used in *any* application we build. 
At present we are using the **synchronous** version for *simplicity* (of the example):
https://github.com/docdis/learn-json-web-tokens/blob/707298b1203276c08bbfca4db682b9be313b1615/example/lib/helpers.js#L82
But this will be a **bottleneck** at *scale*.
Lets keep an eye on it in our NewRelic dashboard. and optimise when required.

**Comment by nelsonic** [comment]
Our Hapi.js Plugin: https://github.com/dwyl/hapi-auth-jwt2
uses the Async version. see: https://github.com/dwyl/hapi-auth-jwt2/blob/f62bf57795e22b97f5c31a2375b68d6e7e6b80e1/lib/index.js#L39

Do we _need_ to encourage others to use async or let them make their own choices?

**Comment by MIJOTHY** [comment]
When would you want to use the sync version?

**Comment by nelsonic** [comment]
@MIJOTHY Good question! 
I think they only created a sync version for "completeness" ...
I cannot conceive of a need for one except for deciding a token at the boot of an app (before anything else has started... But even then, we can just put the initialisation as the callback to the async method.
So yeah, dunno.
How are you BTW? :wink:

**Comment by MIJOTHY** [comment]
Ah ok. Yeah I'm good thanks, been really busy in the run-up to leaving. Found a site like meetup but for Asia called [doorkeeper](http://www.doorkeeperhq.com/), so gonna lurk on that to find some coding stuff.

**Comment by nelsonic** [comment]
good idea on tracking doorkeeper.
super excited for you! 
(never been to asia ... #FinalFrontier :wink: )
might have to come and visit you ...
Have they told you where you are going yet or is it still a "_surprise_"?

**Comment by MIJOTHY** [comment]
[working here](https://www.google.co.uk/maps/place/Kokusai+High+School/@35.6587218,139.6779052,16.75z/data=!4m2!3m1!1s0x0000000000000000:0x69afe2f307c0a0f8)

**Comment by nelsonic** [comment]
Tokyo :city_sunrise: 
Sweet! the students will take you [_drifting_](https://www.youtube.com/watch?v=iuJDhFRDx9M) :car: :wink:
