### ISSUE TITLE
jwt.herokuapp.com responding with X-Access-Token header

### ISSUE THREAD

**Issue by olizilla** [dwyl/learn-json-web-tokens#37]
The demo needs a redeploy...
<img width="601" alt="screenshot 2015-07-29 20 46 05" src="https://cloud.githubusercontent.com/assets/58871/8968042/dfc91236-3632-11e5-9c3a-63d4f5ae55fb.png">

**Comment by nelsonic** [comment]
I've *just* re-deployed so we're using the `authorization` header. :tired_face: 
but noticed the favicon is 404-ing so going to fix that and send in a PR tonight. :moon:

**Comment by nelsonic** [comment]
Fixed: 
![learn-jwt-auth-header](https://cloud.githubusercontent.com/assets/194400/8981598/b04a1346-36b1-11e5-8c8b-fb1a90157877.png)
