### ISSUE TITLE
Inconsistent header capitalisation 

### ISSUE THREAD

**Issue by olizilla** [dwyl/learn-json-web-tokens#38]
https://github.com/dwyl/learn-json-web-tokens/blob/e31141dfa8e34b29af759be1d1a01fe8fbb49ca9/example/lib/helpers.js#L68

`Content-Type` vs `authorization` vs `user-agent`

Headers are case-insensitive, but it still makes me feel wibbly.

**Comment by nelsonic** [comment]
Yeah... this repo/readme is a mess! I've been meaning to aksk someone to be our copy editor...
