### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by scott-w** [dwyl/learn-json-web-tokens#49]
Just felt it was worth pointing out that there's no LICENSE file meaning that any code here can't be safely used in other projects.

I'd like to recommend this repo be licensed under MIT or BSD with the LICENSE.md file.

**Comment by nelsonic** [comment]
@scott-w we usually use GPL-2.0 for our code see: https://github.com/dwyl/intellectual-property
but no reason not to use MIT or BSD for this tutorial/code. Please feel free to submit a PR. :+1:
