### ISSUE TITLE
File-paths error on path.resolve

### ISSUE THREAD

**Issue by JackTierney** [dwyl/learn-json-web-tokens#51]
On cloning exactly the same repo on two different operating systems (mac and ubuntu) and running the tests, the test pass out of the box on the mac, however we have to change the file path on the Ubuntu.

https://github.com/dwyl/learn-json-web-tokens/blob/master/example/lib/helpers.js#L12

to get the tests to run on the Ubuntu we changed the file path to:

```javascript
var filepath = path.resolve(__dirname + '/../views/' + view + '.html');
```

**Comment by nelsonic** [comment]
@JackTierney that change should work on Mac too, so feel free to make a Pull Request with the change. :+1:

**Comment by nelsonic** [comment]
@JackTierney don't forget to :star: :wink:
