### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-json-web-tokens#56]
while we're at it, we could update the devDependencies .. https://david-dm.org/dwyl/learn-json-web-tokens#info=devDependencies

**Comment by pscott-au** [comment]
Have submitted a quick pull request from my fork. Am learning github etc but am keen to help out and I like the feel of this project. If any suggestions or guidance to how I can help out best I am receptive.

**Comment by iteles** [comment]
Thanks @pscott-au, much appreciated! 
@nelsonic will take a look in the next 24 hours.

I'm currently looking to improve how we improve our practices to help with answering exactly that question (for example things like adding beginner/intermediate/advanced labels) and filling out [our contributing guidelines](https://github.com/dwyl/contributing) so if you have any ideas on what we can do to make it easier, let us know! 👍

**Comment by nelsonic** [comment]
Merged #62 🚀
