### ISSUE TITLE
JSON Web Tokens should be avoided?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-json-web-tokens#69]
![image](https://cloud.githubusercontent.com/assets/194400/23905828/2cacf4f4-08c4-11e7-8606-e9c3e7bb7eb5.png)
https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid _classic_ "click-bait" block post which does _not_ actual explain _how/why_ JWT is a "_bad standard_" nor propose a _better_ alternative. Sadly _most_ people won't invest the time to _understand_ the detail so decisions will `continue` to be based on opinions instead of _evidence_.
Read the comments/discussion: https://news.ycombinator.com/item?id=13865459

**Comment by nelsonic** [comment]
Closing as not constructive or evidence-based.

**Comment by paulocoghi** [comment]
Now they are proposing Paseto:

Website: https://paseto.io
Repository: https://github.com/paragonie/paseto
Overview post: https://paragonie.com/blog/2018/03/paseto-platform-agnostic-security-tokens-is-secure-alternative-jose-standards-jwt-etc
