### ISSUE TITLE
Badge Fail

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-json-web-tokens#88]
![image](https://user-images.githubusercontent.com/194400/50628749-4e1f5080-0f31-11e9-8e22-cab5903b3039.png)

We need to update the dependencies on this tutorial so that they we don't have red badges.
+ [ ] Update dependencies see: https://david-dm.org/dwyl/learn-json-web-tokens
+ [ ] Add Codecov script to `.travis.yml` file:
```yml
after_success:
  - bash <(curl -s https://codecov.io/bash)
```
example: https://github.com/dwyl/todo-list-javascript-tutorial/blob/35f546078cfaedf075016b8c6a5b81d18e5e2edf/.travis.yml#L4
+ [ ] Add Hits badge: https://github.com/dwyl/repo-badges#github-repo-hit-counter-
+ [ ] General tidy up. (_if you spot an area for improvement, please comment below_)

**Comment by lumie31** [comment]
Hey @nelsonic, would love to pick this up

**Comment by nelsonic** [comment]
@lumie31 please go for it if you have time. 👍

**Comment by nelsonic** [comment]
@lumie31 thank you for opening PR https://github.com/dwyl/learn-json-web-tokens/pull/95 🎉

**Comment by nelsonic** [comment]
[![codecov](https://codecov.io/gh/dwyl/learn-json-web-tokens/branch/master/graph/badge.svg)](https://codecov.io/gh/dwyl/learn-json-web-tokens)

**Comment by nelsonic** [comment]
Boom! 💥 
![image](https://user-images.githubusercontent.com/194400/50700675-0ee12480-1043-11e9-80ae-5225ec9d6fbd.png)

That looks _much_ better. 🎉
